.TH "GIT\-URL" "1" "January 07, 2016" "git\-url User Manual" ""
.SH NAME
.PP
git\-url \- Integrate Github/Gitlab/Bitbucket into your git workflow
.SH SYNOPSIS
.PP
git\-url [\f[I]options\f[]] <\f[I]command\f[]> [\f[I]URL or path or URL
part\f[]]
.SH DESCRIPTION
.PP
\f[C]git\-url\f[] simplifies working with remote repository hosting
services such as Github or Gitlab by making tedious tasks like cloning,
forking and setting up working environments as easy as possible.
.SH OPTIONS
.PP
All options can also be specified in the \f[C]config.ini\f[], just leave
of the leading slashes (see \f[I]FILES\f[]).
.PP
Many options reuse standard environment variables as their default,
denoted by \f[I]ENV:VARNAME\f[].
These environment variables can be set in a shell startup script such as
\f[I]~.zshrc\f[] or \f[I]~/.zprofile\f[] (for \f[C]zsh\f[] (1)) or
\f[C]~/.bashrc\f[] or \f[C]~/.bash_profile\f[] (for \f[C]bash\f[] (1)).
.SS General Options
.PP
These are the most common options you should override on the command
line as necessary
.TP
.B \-\-clone, ENV:\f[I]\-\-\f[], DEFAULT:"github.com"
Clone repo from this service.
.RS
.RE
.TP
.B \-\-create, ENV:\f[I]\-\-\f[], DEFAULT:false
Create a new repo if it could not be found
.RS
.RE
.TP
.B \-\-debug[=\f[I]LEVEL\f[]], ENV:\f[I]LOGLEVEL\f[], DEFAULT:"error"
Specify logging level.
Can be one of \f[C]trace\f[], \f[C]debug\f[], \f[C]info\f[] or
\f[C]error\f[].
If no level is specified, defaults to \f[C]debug\f[].
If the option is omitted, only errors will be logged.
.RS
.RE
.TP
.B \-\-fork, ENV:\f[I]\-\-\f[], DEFAULT:false
Whether to fork the repository before cloning.
.RS
.RE
.TP
.B \-\-no\-local, ENV:\f[I]\-\-\f[], DEFAULT:false
Don\[aq]t look for the repo in the directories
.RS
.RE
.SS Preference Options
.PP
These settings are best provided via the configuration file (see
\f[I]FILES\f[]) or using environment variables since you won\[aq]t need
to change them often.
.TP
.B \-\-base\-dir=, ENV:\f[I]GITDIR\f[], DEFAULT:"$HOME/build"
The base directory to clone repos to and look for them.
.RS
.RE
.TP
.B \-\-browser=\f[I]BINARY\f[], ENV:\f[I]BROWSER\f[], DEFAULT:"chromium"
The web browser to open URL with.
.RS
.RE
.TP
.B \-\-clone\-opts=, ENV:\f[I]\-\-\f[], DEFAULT:"\-\-depth 1"
Additional command line arguments to pass to \f[I]git\-clone(1)\f[]
.RS
.RE
.TP
.B \-\-editor=\f[I]BINARY\f[], ENV:\f[I]EDITOR\f[], DEFAULT:"vim"
The editor to open files with.
.RS
.RE
.TP
.B \-\-prefer\-ssh, ENV:\f[I]\-\-\f[], DEFAULT:true
Whether to prefer SSH URL over HTTP URL if the remote repository is
owned by the user.
If set to a true value, use \f[I]git\@host:owner/repo_name\f[] URL over
\f[I]https://host/owner/repo_name\f[] URL.
.RS
.RE
.TP
.B \-\-repo\-dirs=, ENV:\f[I]GITDIR_PATH\f[], DEFAULT:[]
The directories to search for repositories.
.RS
.RE
.TP
.B \-\-shell=\f[I]SHELL\f[], ENV:\f[I]SHELL\f[], DEFAULT:"bash"
The shell to use
.RS
.RE
.SS Remote service options
.PP
These options are related to the integration of remote services.
It is recommended to set those using environment variables or the
configuration file (see \f[I]FILES\f[]).
Currently supported:
.IP \[bu] 2
\f[B]Github.com\f[]
.TP
.B \-\-github_api=, ENV:\f[I]\-\-\f[], DEFAULT:"https://api.github.com"
Base URL of the Github API to use.
Meaningful only for Github Enterprise users.
.RS
.RE
.TP
.B \-\-github_token=, ENV:\f[I]GITHUB_TOKEN\f[], DEFAULT:NONE
Your private github token.
the best place to set this is in a shell startup file.
Make sure to keep this private.
For a guide on how to set up a private access token, please refer to
.RS
.PP
<https://help.github.com/articles/creating-an-access-token-for-command-line-use/>
.RE
.TP
.B \-\-github\-user=, ENV:\f[I]GITHUB_USER\f[], DEFAULT:NONE
Your github user name.
.RS
.RE
.IP \[bu] 2
\f[B]Gitlab.com\f[]
.TP
.B \-\-gitlab_api=, ENV:\f[I]\-\-\f[], DEFAULT:"https://gitlab.com/api/v3"
Base URL of the Gitlab API to use.
.RS
.RE
.TP
.B \-\-gitlab\-token=, ENV:\f[I]GITLAB_TOKEN\f[], DEFAULT:NONE
Your private Gitlab token.
The best place to set this is in a shell startup file.
Make sure to keep this private.
.RS
.PP
You can find your personal access token by browsing to
.IP
.nf
\f[C]
<https://gitlab.com/profile/account>
\f[]
.fi
.RE
.TP
.B \-\-gitlab\-user=, ENV:\f[I]GITLAB_USER\f[], DEFAULT:NONE
Your Gitlab user name.
.RS
.RE
.SH LOCATIONS
.PP
Most commands expect a location:
.SS URL of a repository or a file within a repository
.PP
If the location begins with \f[I]http:\f[], \f[I]https:\f[] or
\f[I]git\@\f[], it is interpreted as the URL to a remote repository or a
file within that remote repository.
Fragments are parsed as offsets within a file.
.PP
Examples:
.IP
.nf
\f[C]
git\-url\ shell\ https://github.com/kba/git\-url
\->\ clone\ on\-demand\ and\ open\ shell\ in\ cloned\ local\ repository

git\-url\ edit\ https://github.com/kba/git\-url/blob/master/git\-url.1.md#L123
\->\ clone\ on\-demand\ and\ edit\ git\-url/git\-url.1.md\ at\ line\ 123
\f[]
.fi
.SS Path to a local repository or a file within a local repository:
.PP
Examples:
.IP
.nf
\f[C]
git\-url\ tmux\ /home/me/my\-repo/
\->\ \ Create\ or\ re\-attach\ to\ a\ tmux\ session\ named\ \[aq]my\-repo\[aq]

git\-url\ browse\ my\-repo/file.html
\->\ \ Open\ the\ latest\ version\ of\ file.html\ in\ the\ remote\ service\ that\ hosts\ my\-repo
\f[]
.fi
.SS Shorthand for a remote repository
.PP
If the location is neither an (existing) file nor a URL, git\-url
interprets it as a shorthand notation for a remote repository.
The syntax is
.IP
.nf
\f[C]
[owner/]repo\-name
\f[]
.fi
.PP
The \f[I]owner\f[] defaults to either the \f[I]\-\-github_user\f[] or
the \f[I]gitlab_user\f[] config option, depending on the config setting
of \f[I]\-\-clone\f[] (Default:.
"${clone}").
.PP
Examples:
.IP
.nf
\f[C]
git\-url\ shell\ kba/git\-url
\->\ \ clone\ https://github.com/kba/git\-url\ on\-demand\ and\ open\ a\ shell\ in\ the
\ \ \ \ local\ repository

GITHUB_USER=YOURNAME\ git\-url\ shell\ my\-repository
\->\ \ Clone\ https://github.com/YOURNAME/my\-repository\ on\-demand\ if\ that\ exists
\ \ \ \ remotely\ and\ open\ a\ shell\ in\ the\ local\ repository

git\-url\ \-\-github_user=YOURNAME\ \-\-create\ shell\ my\-repository
\->\ \ Same\ as\ before,\ but\ optionally\ create\ https://github.com/YOURNAME/my\-repository
\ \ \ \ remotely\ using\ the\ API\ if\ it\ doesn\ not\ exist\ yet.
\f[]
.fi
.SH COMMANDS
.PP
Almost all commands clone on\-demand, so they respect the configuration
from the \f[I]OPTIONS\f[] and \f[I]FILES\f[].
.SS browse [location]
.IP \[bu] 2
\f[I]location\f[] \f[I]OPTIONAL\f[] Location to browse
.PP
Open the browser to this file.
Defaults to the current working directory.
.SS edit <location>
.IP \[bu] 2
\f[I]location\f[] \f[B]REQUIRED\f[] Location to edit
.PP
Open the location in an editor.
.PP
Examples:
.IP
.nf
\f[C]
git\-url\ edit\ https://github.com/kba/git\-url
git\-url\ edit\ https://github.com/kba/git\-url/blob/master/git\-url.1.md
git\-url\ edit\ https://github.com/kba/git\-url/blob/master/git\-url.1.md#L121
\ \ \ \ 
\f[]
.fi
.SS help [command or option]
.IP \[bu] 2
\f[I]command or option\f[] \f[I]OPTIONAL\f[] Command to look up
.PP
Open help for subcommand or man page
.SS shell <location>
.IP \[bu] 2
\f[I]location\f[] \f[B]REQUIRED\f[] Location to edit
.PP
Open a shell in the local repository directory
.SS show
.PP
Show the path of the local repository.
.SS tmux
.PP
Attach to or create a tmux session named like the repository.
.SS url
.PP
Get the URL to this file in the online repository.
.SS usage [all|common|github|gitlab|prefs]
.IP \[bu] 2
\f[I]all|common|github|gitlab|prefs\f[] \f[I]OPTIONAL\f[] Tags to
display
.PP
Show usage
.SS version
.PP
Show version information and such
.SH FILES
.PP
Configuration options (see \f[I]OPTIONS\f[]) can be specified in a
configuration file at \f[C]~/.config/git\-url/config.ini\f[], just leave
of the leading dashes.
The format is basic INI: One key\-value pair per line, separated by
\f[I]=\f[] (equal sign).
Multiple values are separated by \f[I],\f[] (comma).
Empty lines and lines prefixed with \f[C];\f[] or \f[C]#\f[] are
ignored.
.PP
Example:
.IP
.nf
\f[C]
#\ use\ iceweasel\ as\ browser
browser\ =\ iceweasel

github_user\ =\ MYUSERNAME

;\ change\ the\ default\ base\ repo\ dirs
repo_dir\ =\ ~/projects,~/dotfiles
\f[]
.fi
.SH SEE ALSO
.PP
\f[C]git(1)\f[], \f[C]curl(1)\f[], \f[C]perl(1)\f[], \f[C]tmux(1)\f[]
.PP
Check out the Github repository for more information at
<https://github.com/kba/git-url>.
.SH AUTHORS
Konstantin Baierer.
